### PR TITLE
Fix wrong link to beetbox.config.yml

### PR DESCRIPTION
**Pull request by theodorosploumis**
Found the error here: http://beetbox.readthedocs.org/en/stable/configuration/#configuration-from-used-roles

### CODE REVIEW

**Comment by thom8** [comment]
Nice find -- thanks!

**Comment by Decipher** [comment]
Ideally we might want to consider having links locked to specific tags? Although that would likely require processing during the RTFD build process....

**Comment by thom8** [comment]
or rather than links here we could list the roles and keep them updated with code changes

**Comment by Decipher** [comment]
Yes, I think that is the most logical solution of all, have documentation as the definitive source....

**Comment by thom8** [comment]
each role could have it's own page/section with a quick description, defaults we implement, then a link to the role defaults.

**Pull request merged**
