### PR TITLE
#74: Supply a default Vagrantfile with the box.

### PR DESCRIPTION
**Pull request by Decipher**
As per #80.

### CODE REVIEW

**Comment by thom8** [comment]
I've run into issues that seem to relate to running `vagrant global-status` from within the `Vagrantfile`. 
It also drastically impacts the performance of vagrant commands as `vagrant global-status` is run once for every VM you have, so 10 VM's = 10 calls to `vagrant global-status`

Can we possibly extract the project path from `~/.vagrant.d/data/machine-index/index` which is where vagrant stores this data, the vagrant ID is just the 1st 7 chars of the machine ID.

You might also need to check `ENV["VAGRANT_HOME"]` in case this has been overridden and use `#{Dir.home}` to support other OS's.

We need to be extra careful as this change can potentially break someones vagrant installation and affect other non beetbox vagrant projects.

**Comment by thom8** [comment]
There's also another issue when referencing a project which doesn't have a `Vagrantfile` called `Vagrantfile`, as you can override `VAGRANT_VAGRANTFILE` this is a common way to allow multiple configurations within a single project.

The active `Vagrantfile` for a project is `vagrantfile_name` in `~/.vagrant.d/data/machine-index/index`

In this case we should probably bail as early as possible as it would either be a non beetbox project or a customised beetbox project.

**Comment by Decipher** [comment]
Issues addressed. However in my case there was no `ENV["VAGRANT_HOME"]` var.

**Comment by thom8** [comment]
You set VAGRANT_HOME to override the default global state directory.
https://www.vagrantup.com/docs/other/environmental-variables.html

In the past I've used this as my base boxes live on my magnetic disk which has more space available,
I'm now actually using a symlink because I ran into issues like this with other plugins.

**Comment by Decipher** [comment]
Sure, support for `VAGRANT_HOME` added.

**Pull request merged**
