### PR TITLE
Feature/grunt

### PR DESCRIPTION
**Pull request by ivangrynenko**
This is a PR attempting to seek advise why the grunt role being ignored. The Vagrantfile had the `r_vagrantfile` variable pointing to a forked repository in our own account.

The local.confing.yml file has this line:
`installed_extras_grunt: yes`
to activate the grunt role.

What might be wrong or what have I missed?

The contributing.md file has very limited information about adding new roles, which I am happy to update once the issue is narrowed down.

### CODE REVIEW

**Comment by thom8** [comment]
@ivrh this grunt role has not been added to the main project so won't be available inside the project base box, you can use a custom tasks or create a PR to add the role to the project.

**Comment by ivangrynenko** [comment]
@thom8 I was under impression that most roles use git submodule, at least some existing roles are submodules. I was thinking the way I added it is the way to add it to the project. What have I missed? Do I need to add the role fles to the project - is that what you mean?

**Comment by thom8** [comment]
@ivrh roles are included as submodules but only roles inside the main project -- https://github.com/beetboxvm/beetbox/tree/master/provisioning/ansible/roles

You would need to set `beet_repo` to your fork so that your own version is checked out before provisioning.

see.
https://github.com/beetboxvm/beetbox/blob/63a604289059f627e8f5b71b260737cd6c055f31/provisioning/ansible/playbook-update.yml#L38-L58

you can also set which branch/tag/commit with `beet_version`

**Comment by thom8** [comment]
@ivrh looking into this role -- you'd also need it's dependencies --> https://github.com/AsianChris/ansible-role-grunt/blob/master/meta/main.yml

However, we already have all the functionality to install grunt as a global package already eg.

```
installed_extras_nodejs: yes
nodejs_npm_global_packages: 
  - name: grunt-cli
```

https://github.com/geerlingguy/ansible-role-nodejs/blob/64eaeceed713a34e902c77e51451b0525f998217/defaults/main.yml#L16

**Comment by thom8** [comment]
Closing this as we already have a role to install npm packages globally.

**Pull request closed without merging**
